### PR TITLE
Update time comparison between asf datasketches and datasketch

### PR DESCRIPTION
**Pull request by c-dickens**

### CODE REVIEW

**Comment by jmalkin** [comment]
I am concerned that this is not a very accurate way to measure average update time. Specifically, starting and stopping 
the timer is not cost-free, so measuring each update by doing that on each sketch seems like it'll distort things. Ideally it's just adding a noise floor in all cases, but I dunno if it'll interact with things like instruction caching in the CPU.

The preferred approach is generally to time adding a bunch of data at once in order to minimize the timer overhead. By using the sequence generator, I think the idea would be to load a bunch of data from there into a local array and then update from the array so that every sketch sees the same inputs in the same order.

**Comment by c-dickens** [comment]
I think the comment about timing was fair criticism.  I have simplified the notebook to test fewer stream lengths but incorporated the timing in the manner that you suggested.  It should be quicker to run and simpler to parse.

**Comment by jmalkin** [comment]
in general for for library we'd expect 8 < 6 or 4.  6 and 4 are harder to predict since they both involve bit twiddling; for 6 we often need to cross byte boundaries while 4 never does but has exceptions.

That they bounce around very close to each other makes me think a fair amount of it is python overhead overwhelming the actual sketch.

**Review by jmalkin — APPROVED** [review]
I'm torn on including some of the data prep in the timing loop, but I think it's not unreasonable as a slightly more realistic test. So this seems good.

**Comment by c-dickens** [comment]
Are you referring to the line `update_data = self.data_bytes[trial][:_n]` ? 
This was the only way I could avoid generating new random variables for each trial.  

If not this, then I'm unsure what data prep you are referring to as the data is generated once in the class instantiation and all trials are executed on the same dataset.

**Comment by c-dickens** [comment]
Also regarding the relative timings between 8 vs 6 and 4: I could run more trials to get closer to your expected outcome, but I think the purpose of this experiment is to show relative performance vs `datasketch`.  We may need many many more trials to get to your expectation in which case I imagine a cpp profile is more suitable anyway.

**Pull request merged**
